[package]
name = "sprsolve"
version = "0.1.0"
authors = ["Changxi Zheng <cxz@cs.columbia.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["multi_thread"]
# The `multi_thread` feature of package `awesome` will ensure that 
# the `multi_thread` feature of the package `sprs` is also enabled.
multi_thread = ["rayon", "sprs/multi_thread"]

[dependencies]
num-traits = "0.2"
num-complex = "0.2"
sprs = { path = "sprs", default-features = false }

rayon = { version = "1.3", optional = true }
