[package]
name = "sprsolve"
version = "0.1.0"
authors = ["Changxi Zheng <cxz@cs.columbia.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-complex = "0.2"
sprs = { path = "sprs" }

